### ISSUE TITLE
Question: Pass custom headers to request

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [kitabisa/sonarqube-action#39]
Apologies for posting a question as an issue, let me know if this is inappropriate so as to close it.

My SQ instance is behind a CloudFlare protected domain therefore currently my GH Action runs fail to communicate with it.

Is there a way to pass a custom header, as in:

```
Cf-Access-Client-Id: XXXXXXXXXX
``` 
to the action?

Thanks in advance

**Comment by dwisiswant0** [comment]
I believe that it is possible to circumvent this by configuring custom rules[^1][^2] settings within Zone-level Web Application Firewall (WAF), instead of arbitrarily implementing it through actions, which is not considered a best practice.

[^1]: Custom rules, https://developers.cloudflare.com/waf/custom-rules/.
[^2]: Create custom rules in the dashboard, https://developers.cloudflare.com/waf/custom-rules/create-dashboard/.
